# Generated by Django 4.2 on 2023-09-12 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category')),
                ('note', models.CharField(blank=True, default='No Note', max_length=50, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Officer')),
                ('phone', models.CharField(default='No_Phone', max_length=14, verbose_name='Phone')),
                ('note', models.CharField(default='No_Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(default='No Descriptions', max_length=50, verbose_name='Describe')),
                ('price', models.FloatField(verbose_name='Price')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('note', models.CharField(default='No_Note', max_length=50, verbose_name='Note')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Unit')),
                ('note', models.CharField(default='No Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(choices=[('Stock_In', 'Stock_In'), ('Stock_Out', 'Stock_Out')], max_length=50)),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('note', models.CharField(default='No_Note', max_length=50, verbose_name='Note')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stock_Transaction', to='stock.stockitem', verbose_name='item')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transaction_Officer', to='stock.officer')),
            ],
        ),
        migrations.AddField(
            model_name='stockitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.uom', verbose_name='Unit'),
        ),
    ]
