# Generated by Django 4.2 on 2023-09-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='uom',
            name='note',
            field=models.CharField(blank=True, default='No Note', max_length=50, null=True, verbose_name='Note'),
        ),
    ]
