# Generated by Django 4.2.4 on 2023-09-05 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('client', models.CharField(max_length=100, verbose_name='Client')),
                ('phone', models.CharField(max_length=14, verbose_name='Phone')),
                ('location', models.TextField(max_length=300, verbose_name='Address')),
                ('email', models.CharField(default='No_Email', max_length=50, verbose_name='Email')),
                ('note', models.CharField(default='No_Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(default='No_Phone', max_length=14, verbose_name='Phone')),
                ('note', models.CharField(default='No_Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Etbaly_Shokran', 'Etbaly_Shokran'), ('Melouk_Eltibah', 'Melouk_Eltibah'), ('Print_Square', 'Print_Square')], max_length=50, verbose_name='Branch')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Confirmed', 'Confirmed'), ('Processed', 'Processed'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Created', max_length=12, verbose_name='Status')),
                ('active', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('FaceBook', 'FaceBook')], max_length=50, verbose_name='Active')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('cash', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cash')),
                ('transfer', models.IntegerField(blank=True, default=0, null=True, verbose_name='Transfer')),
                ('Due_date', models.DateField(blank=True, null=True, verbose_name='Due_date')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount')),
                ('Delivery', models.IntegerField(blank=True, default=0, null=True, verbose_name='Delivery')),
                ('note', models.CharField(default='No_Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('subtitle', models.TextField(default='No_Subtitle', max_length=300, verbose_name='Subtitle')),
                ('note', models.CharField(default='No_Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(default='No_Phone', max_length=14, verbose_name='Phone')),
                ('note', models.CharField(default='No_Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Price')),
                ('note', models.CharField(default='No_Note', max_length=50, verbose_name='note')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_Detail', to='Etpaly_Orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_product', to='Etpaly_Orders.product', verbose_name='product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_Seller', to='Etpaly_Orders.sellers'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_customer', to='Etpaly_Orders.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_Designer', to='Etpaly_Orders.designer'),
        ),
    ]
