# Generated by Django 4.2.4 on 2023-09-02 19:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='client')),
                ('phone', models.CharField(max_length=14, verbose_name='phone')),
                ('location', models.TextField(max_length=300, verbose_name='Address')),
                ('email', models.EmailField(default='no email', max_length=50, verbose_name='email')),
                ('note', models.CharField(default='no note', max_length=50, verbose_name='note')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Confirmed', 'Confirmed'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Created', max_length=12, verbose_name='Status')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Order_date')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery_date')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount')),
                ('Delivery_Fee', models.FloatField(blank=True, default=0, null=True, verbose_name='Delivery_Fee')),
                ('note', models.CharField(default='no note', max_length=50, verbose_name='note')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customer', to='Etpaly_Orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('sku', models.CharField(max_length=10, verbose_name='sku')),
                ('subtitle', models.CharField(max_length=300, verbose_name='subtitle')),
                ('note', models.CharField(default='no note', max_length=50, verbose_name='note')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('note', models.CharField(default='no note', max_length=50, verbose_name='note')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_Detail', to='Etpaly_Orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product', to='Etpaly_Orders.product', verbose_name='product')),
            ],
        ),
    ]
