# Generated by Django 4.2.4 on 2023-08-26 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='client')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('location', models.TextField(max_length=300, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='order')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Confirmed', 'Confirmed'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Created', max_length=12)),
                ('order_time', models.DateField(default=django.utils.timezone.now)),
                ('delivery_time', models.DateField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, default=0, null=True)),
                ('Delivery_Fee', models.FloatField(blank=True, default=0, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customer', to='Etpaly_Orders.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='image')),
                ('price', models.FloatField(verbose_name='price')),
                ('sku', models.IntegerField(verbose_name='sku')),
                ('subtitle', models.CharField(max_length=300, verbose_name='subtitle')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('unit', models.CharField(choices=[('عدد', 'عدد'), ('كيلو', 'كيلو'), ('روزمة', 'روزمة')], max_length=50)),
                ('limit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction', models.CharField(choices=[('Stock_In', 'Stock_In'), ('Stock_Out', 'Stock_Out')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stock_Transaction', to='Etpaly_Orders.stockitem', verbose_name='item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_Detail', to='Etpaly_Orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product', to='Etpaly_Orders.product')),
            ],
        ),
    ]
