# Generated by Django 4.2.4 on 2023-09-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
    ]
