# Generated by Django 4.2.4 on 2023-09-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='no email', max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Delivery_Fee',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Delivery_Fee'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(max_length=15, verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.CharField(default='no subtitle', max_length=300, verbose_name='subtitle'),
        ),
    ]
