# Generated by Django 4.2.4 on 2023-08-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0002_alter_customer_name_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=10, verbose_name='sku'),
        ),
    ]
