# Generated by Django 4.2.4 on 2023-09-03 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0002_remove_product_price_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(default='No_Phone', max_length=14, verbose_name='Phone')),
                ('note', models.CharField(default='No_Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='customer',
            name='client',
            field=models.CharField(default='', max_length=100, verbose_name='Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(default='', max_length=100, verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.CharField(choices=[('Etbaly_Shokran', 'Etbaly_Shokran'), ('Melouk_Eltibah', 'Melouk_Eltibah'), ('Print_Square', 'Print_Square')], default='', max_length=50, verbose_name='Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='client_active',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('FaceBook', 'FaceBook')], default='', max_length=50, verbose_name='Client_Active'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='No_Email', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.CharField(default='No_Note', max_length=50, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(default='No_Note', max_length=50, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='note',
            field=models.CharField(default='No_Note', max_length=50, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(default='No_Note', max_length=50, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.TextField(default='No_Subtitle', max_length=300, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='order',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_Designer', to='Etpaly_Orders.designer'),
        ),
    ]
