# Generated by Django 4.2 on 2023-08-11 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0003_order_delivery_fee_order_discount_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='total',
        ),
    ]
