# Generated by Django 4.2.4 on 2023-09-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0003_designer_remove_customer_name_remove_product_sku_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Delivery_Fee',
            new_name='Delivery',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
    ]
