# Generated by Django 4.2.4 on 2023-09-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0004_alter_orderdetail_price_alter_orderdetail_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Seller',
            new_name='seller',
        ),
    ]
