# Generated by Django 4.2.4 on 2023-08-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0004_alter_order_code_alter_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
    ]
