# Generated by Django 4.2.4 on 2023-09-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0004_rename_delivery_fee_order_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Delivery',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Delivery'),
        ),
    ]
