# Generated by Django 4.2 on 2023-08-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0004_remove_orderdetail_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
