# Generated by Django 4.2.4 on 2023-09-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0005_alter_order_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_active',
            new_name='active',
        ),
    ]
