# Generated by Django 4.2 on 2023-08-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0005_remove_order_total_orderdetail_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction', models.CharField(choices=[('Stock_In', 'Stock_In'), ('Stock_Out', 'Stock_Out')], max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Created', max_length=12),
        ),
        migrations.DeleteModel(
            name='StockIn',
        ),
        migrations.DeleteModel(
            name='StockOut',
        ),
        migrations.AddField(
            model_name='stock_transaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etpaly_Orders.stockitem', verbose_name='item'),
        ),
    ]
