# Generated by Django 4.2.4 on 2023-08-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etpaly_Orders', '0005_remove_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
    ]
